### PR TITLE
Add new option - horse

### PR DESCRIPTION
**Pull request by npot2**
image

Animation

Adding a new option for horse. Light and dark are both added. 

Tested on windows 10.

### CODE REVIEW

**Comment by Kyome22** [comment]
@npot2 
Thanks for your pull request.
Is the horse animation you use copyright free?

**Comment by npot2** [comment]
@Kyome22 

I'm not sure if how the copyright will work on this case.
The animation was inspired by "Sallie Gardner at a Gallop (1878)" - https://www.imdb.com/title/tt2221420/

I removed the rider from the image and used opencv to process and convert to a pixel art. 
Then PIL is used to resize and save as ico.

image

**Comment by Kyome22** [comment]
@npot2 
Since the photographer, Eadweard Muybridge, has been dead for more than 100 years, I think the horse in motion is generally copyright free.

I'll merge this pr.

**Comment by hyjklmn** [comment]
How can I get this horse?

**Comment by npot2** [comment]
> How can I get this horse?

There is no release that has this change yet. You'll either have to wait for the next release or need to build exe by yourself

**Comment by hyjklmn** [comment]
ok,thank you



---Original---
From: ***@***.***&gt;
Date: Mon, May 16, 2022 13:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Kyome22/RunCat_for_windows] Add new option - horse (PR #88)




  
How can I get this horse?
  
There is no release that has this change yet. You'll either have to wait for the next release or need to build exe by yourself

**Comment by Kyome22** [comment]
@hyjklmn @npot2 
Sorry to keep you waiting. I will check the operation today and release it.

**Comment by Kyome22** [comment]
I did.
https://github.com/Kyome22/RunCat_for_windows/releases/tag/1.11

**Comment by hyjklmn** [comment]
ohhhh,thank you！

---Original---
From: "Takuto NAKAMURA ***@***.***&gt;
Date: Sat, Jun 11, 2022 10:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Kyome22/RunCat_for_windows] Add new option - horse (PR #88)




 
I did.
 https://github.com/Kyome22/RunCat_for_windows/releases/tag/1.11

**Pull request merged**
