### PR TITLE
Add HIDPI Aware

### PR DESCRIPTION
**Pull request by qinlili23333**

### CODE REVIEW

**Comment by Kyome22** [comment]
@qinlili23333 
Hi, thank you for the pull request.
What is HIDPI Aware?

**Comment by qinlili23333** [comment]
> @qinlili23333 Hi, thank you for the pull request. What is HIDPI Aware?

if u are using a small screen with wigh resolution, windows will resize application. if hidpi aware is not enabled, windows will do a bitmap resize which leads text or image seems blurry. however hidpi aware makes windows render your  application directly in higher resolution so all objects can be rendered clearly.

**Comment by rstm-sf** [comment]
We can use [Application.SetHighDpiMode](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode) instead of a manifest

**Comment by qinlili23333** [comment]
> We can use [Application.SetHighDpiMode](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode) instead of a manifest



> We can use [Application.SetHighDpiMode](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode) instead of a manifest

Good choice

**Comment by Kyome22** [comment]
I appreciate the suggestions for improvement, but I would like to see a separate proposal for the addition of the GitHub Actions workflow and the addition of HIDPI Aware.

**Pull request closed without merging**
