### PR TITLE
Support ARM64 build

### PR DESCRIPTION
**Pull request by somnisomni**
This pull request will make the app could be built for ARM64 architecture by adding Configurations and Publish Profiles.

### CODE REVIEW

**Comment by Kyome22** [comment]
@somnisomni 
If I merge this PR, do I need to use Visual Studio 2022? (I use Visual Studio 2019 now.)
And, my ThinkPad is probably not ARM64 but is it ok?

**Comment by Kyome22** [comment]
Also, Is it no problem if I merge #97 ?

**Comment by somnisomni** [comment]
I think you don't need to update your Visual Studio, the ARM64 build support was included since VS2017 (as far as I searched). .NET 5 also supports ARM64 build, so there will be no hassle.

Just ignore about `VisualStudioVersion`. or maybe I can remove the changes of it if you want.

**Comment by Kyome22** [comment]
@somnisomni 
OK! 
I want to confirm that these pull requests will work well and merge #95 and #97 over the weekend.

**Pull request merged**
