### PR TITLE
Increased precision of the CPU utilization value

### PR DESCRIPTION
**Pull request by airtaxi**
Applied new PerformanceCounter parameter that matches the CPU usage value of the Windows Task Manager.

### CODE REVIEW

**Comment by somnisomni** [comment]
Ref. https://docs.microsoft.com/en-us/troubleshoot/windows-client/performance/cpu-usage-exceeds-100

The change made by @airtaxi in this PR will use the value which reflects actual processor activity. I recommend to merge this ;)

**Comment by Kyome22** [comment]
@airtaxi 
Do you complete to work in this pull request?

**Comment by airtaxi** [comment]
> @airtaxi Do you complete to work in this pull request?

Yes! it's completed

**Comment by lynkas** [comment]
`new PerformanceCounter("Processor Information", "% Processor Utility", "_Total");` is way too not accurate on my machine, instead I got a more precise result (nearly same as task manager) by this: https://stackoverflow.com/a/46737880/8883824

**Pull request merged**
