### PR TITLE
fix: The color does not match the options.

### PR DESCRIPTION
**Pull request by HChenX**
choose "Light" but is Dark mode.
choose "Dark" but is Light mode. 
If color reversal is required, only default mode can.
I think this is reasonable, thanks

### CODE REVIEW

**Comment by technobird22** [comment]
I believe the theme here is referring to the theme of the Windows taskbar, hence when the taskbar is "Dark", the cat should be white, whereas when the taskbar is "Light", the cat would be dark.

**Comment by Kyome22** [comment]
> hence when the taskbar is "Dark", the cat should be white, whereas when the taskbar is "Light", the cat would be dark.

That's right!

**Comment by HChenX** [comment]
> I believe the theme here is referring to the theme of the Windows taskbar, hence when the taskbar is "Dark", the cat should be white, whereas when the taskbar is "Light", the cat would be dark.

I don't think so, because the setting of software should be based on itself, dark color is dark color, and light color is light color. Why do your software settings point to other software?

**Comment by HChenX** [comment]
> > I believe the theme here is referring to the theme of the Windows taskbar, hence when the taskbar is "Dark", the cat should be white, whereas when the taskbar is "Light", the cat would be dark.
> 
> I don't think so, because the setting of software should be based on itself, dark color is dark color, and light color is light color. Why do your software settings point to other software?

Moreover, I have hardly seen any software click on the dark option to make it light.Maybe I don't know much.

**Pull request closed without merging**
